name = "BitcoinPrimitives"
uuid = "9d766032-97e2-11e9-15bd-efb533ad7bdc"
authors = ["Guido Kraemer <gdkrmr@users.noreply.github.com>", "Simon Castano <simon@brane.cc>"]
repository = "https://gitlab.com/braneproject/BitcoinPrimitives.jl.git"
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
